#!/usr/bin/env ansible-playbook

---
- name: Play 'testlink.ansible.role/setup.yml'
  hosts: all
  vars_files:
    - defaults/main.yml

  pre_tasks:
    - name: Run tassk before roles
      include_tasks: tasks/pre_tasks.yml
      when: ansible_distribution == 'Debian'

  roles:
    - williamyeh.nginx
    - chusiang.php7
    - geerlingguy.mysql

    # Only for development.
    #- chusiang.switch-apt-mirror
    #- chusiang.vim-and-vi-mode

  tasks:
    - name: Include main task
      import_tasks: tasks/main.yml

  handlers:
    - name: Include handler task
      import_tasks: handlers/main.yml

# vim: ft=ansible :
